BOARD_X = 8
BOARD_Y = 8

# UI constants
WIDTH = 500
HEIGHT = 500
PADDING = 30
SIZE_X = (WIDTH-PADDING*2)/BOARD_X
SIZE_Y = (HEIGHT-PADDING*2)/BOARD_Y


HTTP_URL = "http://localhost:5000/"

# TODO, zatial je tu rook
PAWN_DNA = "AHH HAA HAA AHS CHA CHA HHA SAS AAA\t AAA\n AAA"